name = "scheduled-merge-cloudflare-workers"
# account_id = "f8d9cac88285c4d654ba305a92e952d6"
workers_dev = true

main = "worker.ts"
compatibility_date = "2022-12-10"
node_compat = true

# [triggers]
# crons = [ "* * * * *" ]
