name = "scheduled-merge-cloudflare-workers"
account_id = "b9d9f39f61032e736a07fa0653d76c23"
workers_dev = true

main = "worker.ts"
compatibility_date = "2022-12-10"
node_compat = true

[triggers]
crons = [ "*/3 * * * *" ]

[env.staging]

[[ env.staging.d1_databases ]]
binding = "DB"
database_name = "scheduled-merge-staging"
database_id = "5488b320-e35e-4b31-83f8-e9f0e4a3f331"
