name = "scheduled-merge-cloudflare-workers"
account_id = "b9d9f39f61032e736a07fa0653d76c23"
workers_dev = true

main = "worker.ts"
compatibility_date = "2022-12-10"
node_compat = true

# [triggers]
# crons = [ "* * * * *" ]

[env.staging]
